services:
  server:
    image: ghcr.io/tuliptreetech/emerson/lantern:latest
    ports:
      - "10314:10314"
    privileged: true
    platform: linux/amd64
    volumes:
      - ./share:/opt/tuliptree/emerson/projects/armv5-virtio/scratch
      - ./arduino/flash.bin:/opt/tuliptree/emerson/projects/arduino-uno-r3/flash.bin
    environment:
      license_key: ${license_key}
  python-unit-test:
    image: ghcr.io/tuliptreetech/emerson/emerson-python:latest
    platform: linux/amd64
    volumes:
      - ./scripts:/scripts
    command: /scripts/wait-for-it.sh -t 60 -q -s server:10314 -- python /scripts/run_unit_test.py