version: "3.7"
services:
  server:
    image: ghcr.io/tuliptreetech/emerson/lantern:latest
    ports:
      - "10314:10314"
    privileged: true
    volumes:
      - ./arm-examples:/opt/tuliptree/emerson/projects/lantern/scratch
  python:
    image: ghcr.io/tuliptreetech/emerson/emerson-python:latest
    volumes:
      - ./scripts:/tmp/scripts
      - ./wait-for-it.sh:/wait-for-it.sh
    command: /wait-for-it.sh -t 60 -s server:10314 -- python /tmp/scripts/run_aut.py