#!/bin/bash

set -e

cd "$(dirname $0)" && root_directory="$(pwd)"

set +e
echo "[+] installing the emerson control script as root in /usr/local/bin"
sudo cp "$root_directory/emerson" /usr/local/bin/emerson
set -e

echo "[+] installing necessary files for this user in ~/.emerson"
mkdir -p ~/.emerson/share
mkdir -p ~/.emerson/scripts

if [ ! -e "$HOME/.emerson/.env" ]; then
    echo -n "Enter your license key: "
    read license_key
    echo "license_key=$license_key" > "$HOME/.emerson/.env"
fi

cp "$root_directory/emerson" "$HOME/.emerson"
cp "$root_directory/share/hello" "$HOME/.emerson/share"
cp "$root_directory/share/hello-fails" "$HOME/.emerson/share"
cp "$root_directory/share/snake" "$HOME/.emerson/share"
cp "$root_directory/docker-compose.yaml" "$HOME/.emerson/docker-compose.yaml"
cp "$root_directory/scripts/wait-for-it.sh" "$HOME/.emerson/scripts/wait-for-it.sh"
cp "$root_directory/scripts/run_unit_test.py" "$HOME/.emerson/scripts/run_unit_test.py"
cp "$root_directory/scripts/load_sketch.py" "$HOME/.emerson/scripts/load_sketch.py"
cp "$root_directory/scripts/reload_sketch.py" "$HOME/.emerson/scripts/reload_sketch.py"

docker image load -i "$root_directory/emerson-lantern.tar"
docker image load -i "$root_directory/emerson-python.tar"

echo "[+] emerson is successfully installed"
